The next web recreation using HTML-CSS
notrexxx/TNW-RESPONSIVE-HTML-CSS pull request #2
Opened 2021-01-20 20:26 UTC by notrexxx

This is a copy of thenextweb.com using Grid, Flexbox, Media Queries and gradients

2021-01-21 06:31 UTC, elmejdki requested changes
# status: require changes :recycle: 

Hi, Great job guys :clap: :clap: :clap: but there are some small changes :toolbox: :hammer: :wrench: that you need to take care of, in order for this project to get approved :checkered_flag: 

I loved :heart: how you did handle different CSS file, for each viewport, great job :tophat: 

Please check the comments below:
:point_down: :point_down: :point_down: :point_down: :point_down:

## Required Changes :red_circle::

- [x] Write a proper description for your project on the readme file, give it a proper name, and also use good screenshots of the project:
![image](https://user-images.githubusercontent.com/34653764/105288269-1f2bb400-5bb8-11eb-8cbe-575ec411fadc.png)

- [x] Fix the screenshot image link in your readme
![image](https://user-images.githubusercontent.com/34653764/105283854-96aa1500-5bb1-11eb-9a14-9c2ac2285897.png)

- [ ] Fix your profile links on the readme.

- [x] Fix the header on desktop view:

|*Clone*|*Original*|
|---|----|
| ![image](https://user-images.githubusercontent.com/34653764/105284049-ef79ad80-5bb1-11eb-987c-3ebe67606035.png) | ![image](https://user-images.githubusercontent.com/34653764/105284071-fdc7c980-5bb1-11eb-9c35-044703f1848d.png) |

- It contains main navigation row
- It contains sub-navigation row
- It contains a search icon at the rightmost side of sub-navigation row
- There should be no logo on the left side corner please follow the original design.

- [ ] Fix the header on tablet view:

|*Clone*|*Original*|
|:----:|:-------:|
| ![image](https://user-images.githubusercontent.com/34653764/105284478-d3c2d700-5bb2-11eb-91e1-6ae3541d19bd.png) | ![image](https://user-images.githubusercontent.com/34653764/105284445-c1e13400-5bb2-11eb-8883-f698047488c8.png) |

- [ ] Fix the header on Mobile view they should match correctly:

|*Clone*|*Original*|
|:-----:|:------:|
| ![image](https://user-images.githubusercontent.com/34653764/105284616-20a6ad80-5bb3-11eb-9db3-fea4fd82ee4b.png) | ![image](https://user-images.githubusercontent.com/34653764/105284591-15538200-5bb3-11eb-9c71-7375d88ed1f3.png) |

- [x] Fix the hero section align correctly the title inside each image like it is on the original page:

|*Clone*|*Original*|
|:----:|:----:|
| ![image](https://user-images.githubusercontent.com/34653764/105284867-9a3e9b80-5bb3-11eb-82c1-c67eaf63d98c.png) | ![image](https://user-images.githubusercontent.com/34653764/105284899-a6c2f400-5bb3-11eb-9ea2-b2a07e172251.png) |

- also you should have a tnw logo on the bigger image on the left.

- [x] align the latest news correctly with the articles and give it a correct size:

|*Clone*|*Original*|
|:----:|:----:|
| ![image](https://user-images.githubusercontent.com/34653764/105285339-7d569800-5bb4-11eb-8f57-f95bae7b5925.png) | ![image](https://user-images.githubusercontent.com/34653764/105285353-85aed300-5bb4-11eb-8b27-c5d35cd9fa24.png) |

- [ ] Fix the latest funding section on the desktop view, align correctly the headlines and also you are messing another article there are supposed to be 4 articles:

|*Clone*|*Original*|
|:-----:|:------:|
| ![image](https://user-images.githubusercontent.com/34653764/105285593-fe159400-5bb4-11eb-8ff3-cd1d928dd351.png) | ![image](https://user-images.githubusercontent.com/34653764/105285566-f229d200-5bb4-11eb-940e-c04aeaa98bf6.png) |

- 4 articles on desktop view
- 3 articles on tablet view
- and 1 article per row on a mobile view

- [ ] on the section below the latest funding section you should have three articles per row on desktop view please fix it(on mobile and tablet view you are good):

|*Clone*|*Original*|
|:----:|:-----:|
| ![image](https://user-images.githubusercontent.com/34653764/105285782-64021b80-5bb5-11eb-9929-3e9dfcde300a.png) | ![image](https://user-images.githubusercontent.com/34653764/105285765-59e01d00-5bb5-11eb-9c68-60937109b090.png) |

- [ ] Fix the headlines on the latest deals section on desktop and mobile views:

|*Clone*|*Original*|
|:-----:|:------:|
| ![image](https://user-images.githubusercontent.com/34653764/105285949-aaf01100-5bb5-11eb-851e-c52b51de2d7c.png) | ![image](https://user-images.githubusercontent.com/34653764/105285981-b7746980-5bb5-11eb-8981-978580f5705f.png) |

- [ ] The articles below the latest funding section are going out of the screen please position them correctly and also resize them correctly:
![image](https://user-images.githubusercontent.com/34653764/105286325-54cf9d80-5bb6-11eb-96ae-20fae17b53c2.png)

## Optional:

- [ ] Change the icons into white icons:
![image](https://user-images.githubusercontent.com/34653764/105286040-da9f1900-5bb5-11eb-938a-be4974fba2ce.png)

- [ ] add the off percent on the latest deals section articles:
![image](https://user-images.githubusercontent.com/34653764/105286464-a1b37400-5bb6-11eb-9653-d36b30f69d24.png)

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you have any questions or need help don't hesitate to contact me on slack, I would love to help_
## _Zakariae El Mejdki_

2021-01-21 23:35 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [ ] Let's fix this minor issue, you are to have just three items not four
 
##### Yours
![2](https://user-images.githubusercontent.com/23278161/105425402-9c533980-5c49-11eb-95a3-3a45efad8d94.png)
##### Original
![1](https://user-images.githubusercontent.com/23278161/105425439-b1c86380-5c49-11eb-905c-52bc50c68631.png)


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2021-01-22 00:10 UTC, notrexxx commented
> ## Hi Team ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png)
> #### Great Job so far, everything works fine, but there are a few more things required.
> ### General
> * [x]  Let's fix this minor issue, you are to have just three items not four
> 
> ##### Yours
> ![2](https://user-images.githubusercontent.com/23278161/105425402-9c533980-5c49-11eb-95a3-3a45efad8d94.png)
> 
> ##### Original
> ![1](https://user-images.githubusercontent.com/23278161/105425439-b1c86380-5c49-11eb-905c-52bc50c68631.png)
> 
> ### Make changes and submit another code review request.
> _Happy coding_
> (Any questions Feel free to contact me on slack @kobiyoyo)

Hello!

Thank you so much for the input.

I have hidden the investment tab on the mobile viewport and committed it!.

Regards.

2021-01-22 01:39 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @notrexxx  & @EroAuditore**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] make sure that you get the right color for the icons in the navbar.
- [ ] in the original page there is a margin on both sides of the page but in yours, there isn't. you can create the same effect by giving the main divs a max-width and setting the margin to auto. 


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-01-22 06:51 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @notrexxx and @EroAuditore 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [ ] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
- [ ] Live link is not working in README file
- [ ] Add `#` in all empty `href` attributes

### Navbar
- [ ] Please fix the responsive issues

|[Source Page](https://thenextweb.com/)|[Clone Page](https://rawcdn.githack.com/notrexxx/TNW-RESPONSIVE-HTML-CSS/Responsive/wip/index.html)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/105456988-ecf97f80-5ca7-11eb-93fc-38e7a4a742aa.png)|![clone](https://user-images.githubusercontent.com/29689273/105456982-eb2fbc00-5ca7-11eb-832c-0286357a7588.png)|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-01-22 06:51 UTC, umairarshadbutt commented on styles/desktop.css
> +  margin: 0 !important;
Remove `!important` from complete CSS files

2021-01-22 06:51 UTC, umairarshadbutt commented on styles/mobile.css
> +  font-size: 18px !important;
Remove `!important` from complete CSS files

2021-01-22 06:51 UTC, umairarshadbutt commented on styles/tablet.css
> +  font-size: 18px !important;
Remove `!important` from complete CSS files

2021-01-22 06:51 UTC, umairarshadbutt commented on index.html
> +          <a href="">
Add `#` in all empty `href` attributes

2021-01-22 13:55 UTC, notrexxx commented
> # Status: REQUIRED CHANGES ⚠️ 🚧
> Hi @notrexxx and @EroAuditore
> Good job with the changes! 🎉 We are almost there.
> We, however, do have a few changes to carry out before we proceed (see review comment).
> 
> For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
> 
> * [x]  Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
> * [x]  Live link is not working in README file
> * [x]  Add `#` in all empty `href` attributes
> 
> ### Navbar
> * [x]  Please fix the responsive issues
> 
> [Source Page](https://thenextweb.com/)	[Clone Page](https://rawcdn.githack.com/notrexxx/TNW-RESPONSIVE-HTML-CSS/Responsive/wip/index.html)
> ![source-page](https://user-images.githubusercontent.com/29689273/105456988-ecf97f80-5ca7-11eb-93fc-38e7a4a742aa.png)	![clone](https://user-images.githubusercontent.com/29689273/105456982-eb2fbc00-5ca7-11eb-832c-0286357a7588.png)
> * **When you have made the specified changes, please submit another code review. Thank you!**
> 
> **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
> HAPPY CODING 💻
> **[Umair Arshad](https://umairarshad.me/)**
> [Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

LInk is live

2021-01-22 16:11 UTC, ElijahTobs approved these changes
# Status: Approved! :tada: 

## Congratulations Team :medal_sports:  

Good job implementing the changes requested by the previous TSEs.

## You can now merge and submit.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2021-01-22 16:29 UTC, merged